/**
 * Print all SQL migrations in supabase/migrations in filename (lexicographic) order.
 *
 * Use cases:
 * - Copy/paste once into Supabase Dashboard SQL Editor when direct DB connections (5432) are blocked.
 *
 * Examples:
 *   npm run db:migrations:print > /tmp/all-migrations.sql
 *   npm run db:migrations:copy:mac   # copies to clipboard (macOS)
 */

import fs from "node:fs";
import path from "node:path";

function main() {
  const repoRoot = process.cwd();
  const migrationsDir = path.join(repoRoot, "supabase", "migrations");

  if (!fs.existsSync(migrationsDir)) {
    console.error(`❌ migrations dir not found: ${migrationsDir}`);
    process.exit(1);
  }

  /**
   * IMPORTANT:
   * Some migrations have dependencies that are not captured by simple
   * lexicographic ordering (e.g. api_keys/notifications reference organizations).
   * We enforce a small, explicit ordering for known dependencies, and fall back
   * to lexicographic for the rest.
   */
  const preferredOrder: string[] = [
    // Core tables must exist before anything that alters them.
    "20241204_create_core_tables.sql",
    // Embedding column + functions reference documents.
    "20241205_add_pgvector.sql",
    // Enable RLS on core tables (later migrations may override policies).
    "20241205_enable_rls.sql",
    // Organizations must exist before anything referencing them.
    "20241206_add_organizations.sql",
    "20241206_add_api_keys.sql",
    "20241206_add_notifications.sql",
  ];

  const rank = new Map<string, number>(
    preferredOrder.map((name, idx) => [name, idx]),
  );

  const files = fs
    .readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort((a, b) => {
      const ra = rank.has(a) ? (rank.get(a) as number) : Number.POSITIVE_INFINITY;
      const rb = rank.has(b) ? (rank.get(b) as number) : Number.POSITIVE_INFINITY;
      if (ra !== rb) return ra - rb;
      return a.localeCompare(b);
    });

  if (files.length === 0) {
    console.error(`❌ no .sql migrations found in: ${migrationsDir}`);
    process.exit(1);
  }

  const chunks: string[] = [];
  chunks.push("-- =============================================");
  chunks.push("-- DocuFlow: Combined migrations");
  chunks.push("-- Generated by scripts/print-all-migrations.ts");
  chunks.push("-- =============================================");
  chunks.push("");

  for (const file of files) {
    const fullPath = path.join(migrationsDir, file);
    const sql = fs.readFileSync(fullPath, "utf8").replace(/\r\n/g, "\n");

    chunks.push("-- ---------------------------------------------");
    chunks.push(`-- BEGIN MIGRATION: ${file}`);
    chunks.push("-- ---------------------------------------------");
    chunks.push(sql.trimEnd());
    chunks.push("");
    chunks.push("-- ---------------------------------------------");
    chunks.push(`-- END MIGRATION: ${file}`);
    chunks.push("-- ---------------------------------------------");
    chunks.push("");
  }

  process.stdout.write(chunks.join("\n"));
}

main();


